global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: <your_email>@gmail.com
    from: <your_email>@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: <your_email>@gmail.com
    auth_identity: <your_email>@gmail.com
    # setup app password https://support.google.com/accounts/answer/185833?hl=en
    auth_password: <app_password>
    send_resolved: true