version: '3'

networks:
  traefik:
    external: true
    
# https://github.com/AdguardTeam/AdGuardHome

services:
  adguard:
    image: adguard/adguardhome:${ADGUARD_DOCKER_TAG:-latest}
    container_name: ${ADGUARD_CONTAINER_NAME:-adguard} 
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./etc/adguard/conf:/opt/adguardhome/conf
      - ./etc/adguard/work:/opt/adguardhome/work
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${ADGUARD_CONTAINER_NAME:-adguard}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.routers.adguard.rule=Host(`${ADGUARD_CONTAINER_NAME:-adguard}.${HOST_DOMAIN}`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
