networks:
  traefik:
    external: true

# description: A lightweight server monitoring hub with historical data, docker stats, and alerts.
# https://github.com/henrygd/beszel
# https://github.com/henrygd/beszel/blob/main/hub/docker-compose.yml

services:
  beszel:
    image: henrygd/beszel:${BESZEL_DOCKER_TAG:-latest}
    container_name: ${BESZEL_CONTAINER_NAME:-beszel}
    restart: ${BESZEL_RESTART:-unless-stopped}
    mem_limit: ${BESZEL_MEM_LIMIT:-200g}
    networks:
      - traefik
    volumes:
      - ./etc/beszel:/beszel_data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${BESZEL_HOST_NAME:-beszel}.${HOST_DOMAIN}
      - traefik.enable=${BESZEL_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.rule=Host(`${BESZEL_HOST_NAME:-beszel}.${HOST_DOMAIN}`)
      #- traefik.http.services.beszel.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - com.centurylinklabs.watchtower.enable=${BESZEL_WATCHTOWER_ENABLED:-true}
      - autoheal=${BESZEL_AUTOHEAL_ENABLED:-true}
