version: '3'

networks:
  traefik:
    external: true

# https://hub.docker.com/r/google/cadvisor/

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_DOCKER_TAG:-latest}
    container_name: cadvisor
    restart: unless-stopped
    networks:
      - traefik
    command:
      - -allow_dynamic_housekeeping=false
      - -housekeeping_interval=30s
      - -storage_duration=1m0s
      - -docker_only=true
      #- -disable_metrics=accelerator,cpu_topology,disk,memory_numa,hugetlb,cpuset,advtcp,memory_numa
    #privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - org.label-schema.group=monitoring
      - joyride.host.name=cadvisor.${HOST_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.cadvisor.rule=Host(`cadvisor.${HOST_DOMAIN}`)
      - traefik.http.routers.cadvisor.entrypoints=websecure
      - traefik.http.routers.cadvisor.tls=true
      - traefik.http.routers.cadvisor.tls.certresolver=letsencrypt
      - traefik.http.services.cadvisor.loadbalancer.server.scheme=http
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080