version: '3'

networks:
  traefik:
    external: true

# description: Traefik Bouncer for CrowdSec
# https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin

services:
  crowdsec-traefik-bouncer:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:${TRAEFIK_BOUNCER_DOCKER_TAG:-latest}
    container_name: ${TRAEFIK_BOUNCER_CONTAINER_NAME:-traefik-bouncer}
    restart: ${TRAEFIK_BOUNCER_RESTART:-unless-stopped}
    environment:
      - CROWDSEC_AGENT_HOST=crowdsec:8080
      - CROWDSEC_BOUNCER_API_KEY=${TRAEFIK_BOUNCER_API_KEY}
    depends_on:
      - crowdsec
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
