version: '3'

networks:
  default:
    name: traefik

# https://github.com/amir20/dozzle

services:
  dozzle-host:
    image: amir20/dozzle:${DOZZLE_DOCKER_TAG:-latest}
    container_name: ${DOZZLE_CONTAINER_NAME:-dozzle}
    restart: ${DOZZLE_RESTART:-unless-stopped}
    environment:
      - DOZZLE_LEVEL=${DOZZLE_LEVEL:-debug}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - joyride.host.name=${DOZZLE_CONTAINER_NAME:-dozzle}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`${DOZZLE_CONTAINER_NAME:-dozzle}.${HOST_DOMAIN}`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.services.dozzle.loadbalancer.server.scheme=http
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

    # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${DOZZLE_FLAME_NAME:-Dozzle} 
      - flame.url=https://${DOZZLE_CONTAINER_NAME:-dozzle}.${HOST_DOMAIN}
      - flame.icon=${DOZZLE_FLAME_ICON:-math-log} # optional, default is "docker"