version: '3'

networks:
  default:
    name: traefik
    
# https://christitus.com/why-we-dont-browse-the-internet-anymore/
# https://www.youtube.com/watch?v=nxV0CPNeFxY

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:${FRESHRSS_DOCKER_TAG:-latest}
    container_name: ${FRESHRSS_CONTAINER_NAME:-freshrss} 
    restart: ${FRESHRSS_RESTART:-unless-stopped}
    volumes:
      - ./etc/freshrss:/config  
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${FRESHRSS_CONTAINER_NAME:-freshrss}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.freshrss.entrypoints=websecure
      - traefik.http.routers.freshrss.rule=Host(`${FRESHRSS_CONTAINER_NAME:-freshrss}.${HOST_DOMAIN}`)
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${FRESHRSS_FLAME_NAME:-FreshRSS} 
      - flame.url=https://${FRESHRSS_CONTAINER_NAME:-freshrss}.${HOST_DOMAIN}
      - flame.icon=${FRESHRSS_FLAME_ICON:-newspaper-variant-outline} # optional, default is "docker"
