version: '3'

networks:
  traefik:
    external: true

# <================= add links to documentation here =================>

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:${FRIGATE_DOCKER_TAG:-master-6bcf44a-tensorrt}
    container_name: ${FRIGATE_CONTAINER_NAME:-frigate}
    restart: ${FRIGATE_RESTART:-unless-stopped}
    networks:
      - traefik
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./etc/frigate/config.yml:/config/config.yml
      - ./etc/frigate/frigate.db:/database/frigate.db
      - /apps/trt-models/trt-models:/trt-models
      - /mnt/apps/frigate:/media/frigate
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PLUS_API_KEY=${FRIGATE_PLUS_API_KEY:-}
      - FRIGATE_RTSP_USER=${FRIGATE_RTSP_USER:-}
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD:-}
      - FRIGATE_MQTT_USER=${FRIGATE_MQTT_USER:-}
      - FRIGATE_MQTT_PASSWORD=${FRIGATE_MQTT_PASSWORD:-}
    ports:
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
              #count: 1 # number of GPUs
              capabilities: [gpu]
    labels:
      - joyride.host.name=${FRIGATE_CONTAINER_NAME:-frigate}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.frigate.entrypoints=websecure
      - traefik.http.routers.frigate.rule=Host(`${FRIGATE_CONTAINER_NAME:-frigate}.${HOST_DOMAIN}`)
      - traefik.http.services.frigate.loadbalancer.server.port=5000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
