version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/_/ghost

services:
  ghost:
    image: ghost:${GHOST_DOCKER_TAG:-alpine}
    container_name: ${GHOST_CONTAINER_NAME:-ghost} 
    restart: ${GHOST_RESTART:-unless-stopped}
    volumes:
      - ./etc/ghost:/var/lib/ghost/content
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - url=${GHOST_URL}
      - database__client=mysql
      - database__connection__host=${GHOST_DATABASE_HOST:-mariadb}
      - database__connection__user=${GHOST_DATABASE_USER:-ghost}
      - database__connection__password=${GHOST_DATABASE_PASSWORD:-you_should_really_consider_changing_this}
      - database__connection__database=${GHOST_DATABASE_NAME:-ghost}
    labels:
      - joyride.host.name=${GHOST_CONTAINER_NAME:-ghost}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.ghost.entrypoints=websecure
      - traefik.http.routers.ghost.rule=Host(`${GHOST_CONTAINER_NAME:-ghost}.${HOST_DOMAIN}`)
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${GHOST_FLAME_NAME:-ghost} 
      - flame.url=${GHOST_CONTAINER_NAME:-ghost}.${HOST_DOMAIN}
      - flame.icon=${GHOST_FLAME_ICON:-docker} # optional, default is "docker"