networks:
  traefik:
    external: true

# description: <= put a brief description of glance here =>
# https://github.com/glanceapp/glance

services:
  glance:
    image: glanceapp/glance:${GLANCE_DOCKER_TAG:-latest}
    container_name: ${GLANCE_CONTAINER_NAME:-glance}
    restart: ${GLANCE_RESTART:-unless-stopped}
    mem_limit: ${GLANCE_MEM_LIMIT:-200g}
    networks:
      - traefik
    volumes:
      - ./etc/glance/glance.yml:/app/glance.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${GLANCE_HOST_NAME:-glance}.${HOST_DOMAIN}
      - traefik.enable=${GLANCE_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.glance.entrypoints=websecure
      - traefik.http.routers.glance.rule=Host(`${GLANCE_HOST_NAME:-glance}.${HOST_DOMAIN}`)
      #- traefik.http.services.glance.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.glance.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${GLANCE_WATCHTOWER_ENABLED:-true}
      - autoheal=${GLANCE_AUTOHEAL_ENABLED:-true}
