networks:
  traefik:
    external: true

# description: A clientless remote desktop gateway.
# https://github.com/jwetzell/docker-guacamole
# The default username is guacadmin with password guacadmin.
# https://guacamole.apache.org/doc/gug/

services:
  guacamole:
    image: jwetzell/guacamole:${GUACAMOLE_DOCKER_TAG:-latest}
    container_name: ${GUACAMOLE_CONTAINER_NAME:-guacamole}
    restart: ${GUACAMOLE_RESTART:-unless-stopped}
    mem_limit: ${GUACAMOLE_MEM_LIMIT:-200g}
    networks:
      - traefik
    volumes:
      - ./etc/guacamole:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - EXTENSIONS=${GUACAMOLE_EXTENSIONS:-vault}
    labels:
      - joyride.host.name=${GUACAMOLE_CONTAINER_NAME:-guacamole}.${HOST_DOMAIN}
      - traefik.enable=${GUACAMOLE_TRAEFIK_ENABLED:-true}
      - traefik.http.routers.guacamole.entrypoints=websecure
      - traefik.http.routers.guacamole.rule=Host(`${GUACAMOLE_CONTAINER_NAME:-guacamole}.${HOST_DOMAIN}`)
      #- traefik.http.services.guacamole.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.guacamole.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${GUACAMOLE_WATCHTOWER_ENABLED:-true}
      - autoheal=${GUACAMOLE_AUTOHEAL_ENABLED:-true}
