networks:
  traefik:
    external: true

# description: Dashboard for managing self-hosted services
# https://hay-kot.github.io/homebox/
# https://hay-kot.github.io/homebox/quick-start/

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:${HOMEBOX_DOCKER_TAG:-latest}
    container_name: ${HOMEBOX_CONTAINER_NAME:-homebox}
    restart: ${HOMEBOX_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/homebox:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=100
    labels:
      - joyride.host.name=${HOMEBOX_CONTAINER_NAME:-homebox}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.homebox.entrypoints=websecure
      - traefik.http.routers.homebox.rule=Host(`${HOMEBOX_CONTAINER_NAME:-homebox}.${HOST_DOMAIN}`)
      - traefik.http.services.homebox.loadbalancer.server.port=7745
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
