networks:
  traefik:
    external: true

# description: IT documentation, ticketing and accounting system.
# https://itflow.org/

services:
  itflow:
    image: lued/itflow:${ITFLOW_DOCKER_TAG:-latest}
    container_name: ${ITFLOW_CONTAINER_NAME:-itflow}
    hostname: ${ITFLOW_HOSTNAME:-itflow}
    restart: ${ITFLOW_RESTART:-unless-stopped}
    networks:
      - traefik
    depends_on:
      - itflow-db
    volumes:
      - ./etc/itflow/www:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.itflow.entrypoints=websecure
      - traefik.http.routers.itflow.rule=Host(`${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}`)
      - traefik.http.services.itflow.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=${ITFLOW_WATCHTOWER_ENABLED:-true}
      - autoheal=true
