version: '3'

networks:
  traefik:
    external: true

# https://itflow.org/

services:
  itflow:
    image: lued/itflow:${ITFLOW_DOCKER_TAG:-latest}
    container_name: ${ITFLOW_CONTAINER_NAME:-itflow}
    hostname: ${ITFLOW_HOSTNAME:-itflow}
    restart: ${ITFLOW_RESTART:-unless-stopped}
    networks:
      - traefik
    depends_on:
      - itflow-db
    volumes:
      - ./etc/itflow:/config # <==== this probably needs changed
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.itflow.entrypoints=websecure
      - traefik.http.routers.itflow.rule=Host(`${ITFLOW_CONTAINER_NAME:-itflow}.${HOST_DOMAIN}`)
      #- traefik.http.services.itflow.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.itflow.loadbalancer.server.port=8096
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
