version: '3'

# https://github.com/Fallenbagel/jellyseerr/tree/develop

services:
  jellyseer:
    image: fallenbagel/jellyseer:${JELLYSEER_DOCKER_TAG:-latest}
    container_name: ${JELLYSEER_CONTAINER_NAME:-jellyseer}
    restart: ${JELLYSEER_RESTART:-unless-stopped}
    volumes:
      - ./etc/jellyseer:/config # <==== this probably needs changed
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${JELLYSEER_CONTAINER_NAME:-jellyseer}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.jellyseer.entrypoints=websecure
      - traefik.http.routers.jellyseer.rule=Host(`${JELLYSEER_CONTAINER_NAME:-jellyseer}.${HOST_DOMAIN}`)
      #- traefik.http.services.jellyseer.loadbalancer.server.scheme=https # enable if the service wants to connect over>
      - traefik.http.services.jellyseer.loadbalancer.server.port=5055
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
