version: '3'

# description: Web-based dashboard for monitoring services
# https://github.com/ilude/joyride

# if you want to run joyride on port 53
# run the following commands on ubuntu
# sudo systemctl disable systemd-resolved.service
# sudo systemctl stop systemd-resolved
#
# then add your primary dns servers ip address
# to /etc/resolv.conf

services:
  joyride:
    image: ghcr.io/traefikturkey/joyride:${JOYRIDE_DOCKER_TAG:-latest}
    container_name: ${JOYRIDE_CONTAINER_NAME:-joyride}
    restart: ${JOYRIDE_RESTART:-unless-stopped}
    environment:
      - HOSTIP=${HOSTIP}
      - JOYRIDE_NXDOMAIN_ENABLED=${JOYRIDE_NXDOMAIN_ENABLED:-false}
      - JOYRIDE_LOG_DEBUG=${JOYRIDE_LOG_DEBUG:-false}
      - JOYRIDE_LOG_QUERIES=${JOYRIDE_LOG_QUERIES:-false}
    ports:
      - ${JOYRIDE_PORT:-54}:54/udp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/joyride/hosts.d:/etc/hosts.d:ro
    labels:
      - traefik.enable=false
