version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/kasm

services:
  kasm:
    image: lscr.io/linuxserver/kasm:${KASM_DOCKER_TAG:-latest}
    container_name: ${KASM_CONTAINER_NAME:-kasm} 
    restart: ${KASM_RESTART:-unless-stopped}
    privileged: true
    volumes:
      - ./etc/kasm/data:/opt
      - ./etc/kasm/profiles:/profiles
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${KASM_CONTAINER_NAME:-kasm}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.kasm.entrypoints=websecure
      - traefik.http.routers.kasm.rule=Host(`${KASM_CONTAINER_NAME:-kasm}.${HOST_DOMAIN}`)
      - traefik.http.services.kasm.loadbalancer.server.scheme=https
      - traefik.http.services.kasm.loadbalancer.server.port=443
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${KASM_FLAME_NAME:-kasm} 
      - flame.url=https://${KASM_CONTAINER_NAME:-kasm}.${HOST_DOMAIN}
      - flame.icon=${KASM_FLAME_ICON:-docker} # optional, default is "docker"