version: '3'

networks:
  traefik:
    external: true

services:
  komga:
    image: ghcr.io/gotson/komga:${KOMGA_DOCKER_TAG:-latest}
    container_name: ${KOMGA_CONTAINER_NAME:-komga}
    restart: ${KOMGA_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ${KOMGA_CONFIG_VOLUME:-./etc/komga}:/config
      - ${MEDIA_MANGA_VOLUME:-./media/manga}:/manga
      - ${MEDIA_COMICS_VOLUME:-./media/comics}:/comics
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${KOMGA_CONTAINER_NAME:-komga}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.komga.entrypoints=websecure
      - traefik.http.routers.komga.rule=Host(`${KOMGA_CONTAINER_NAME:-komga}.${HOST_DOMAIN}`)
      #- traefik.http.services.komga.loadbalancer.server.scheme=https # enable if the service wants to connect over https
      - traefik.http.services.komga.loadbalancer.server.port=25600
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels

      - flame.type=application # "app" works too
      - flame.name=${KOMGA_FLAME_NAME:-komga}
      - flame.url=https://${KOMGA_CONTAINER_NAME:-komga}.${HOST_DOMAIN}
      - flame.icon=${KOMGA_FLAME_ICON:-docker} # optional, default is "docker"
