networks:
  traefik:
    external: true

# description: Self-hosted internet speed test tool
# https://hub.docker.com/r/linuxserver/librespeed
# https://github.com/linuxserver/docker-librespeed

services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:${LIBRESPEED_DOCKER_TAG:-latest}
    container_name: librespeed
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./etc/librespeed:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - PASSWORD=${LIBRESPEED_PASSWORD}
    labels:
      - joyride.host.name=librespeed.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.librespeed.entrypoints=websecure
      - traefik.http.routers.librespeed.rule=Host(`librespeed.${HOST_DOMAIN}`)
      - traefik.http.services.librespeed.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
