networks:
  traefik:
    external: true

# description: Manages music collections and downloads
# https://hub.docker.com/r/linuxserver/lidarr

services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./etc/lidarr:/config
      - ${LIDARR_MUSIC_VOLUME:-./media/music}:/music
      - ${LIDARR_DOWNLOADS_VOLUME:-./media/downloads}:/downloads
      # - /dev/rtc:/dev/rtc:ro
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=lidarr.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${HOST_DOMAIN}`)
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
