version: '3'

networks:
  traefik:
    external: true
    
# https://github.com/minio/minio

# volumes:
#   minio:
#     labels:
#       - remove_volume_on=down
#     driver_opts:
#       type: nfs
#       o: "addr=${MINIO_ROOT_NFS_SERVER:-${NFS_SERVER}},nolock,noatime,soft,rw"
#       device: ":${MINIO_ROOT_NFS_SERVER_PATH:-${NFS_MINIO_PATH}}"

services:
  minio:
    image: minio/minio:${MINIO_DOCKER_TAG:-latest}
    container_name: ${MINIO_CONTAINER_NAME:-minio} 
    restart: ${MINIO_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/minio:/data # <==== this probably needs changed 
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
    labels:
      - joyride.host.name=${MINIO_CONTAINER_NAME:-minio}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.rule=Host(`${MINIO_CONTAINER_NAME:-minio}.${HOST_DOMAIN}`)
      - traefik.http.services.minio.loadbalancer.server.port=9001
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
