version: '3'

# description: Web-based ip address management (ipam) and data center infrastructure management (dcim) tool
# https://docs.linuxserver.io/images/docker-netbox
networks:
  traefik:
    external: true

# https://docs.linuxserver.io/images/docker-netbox

volumes:
  netbox-redis:

services:
  netbox:
    image: lscr.io/linuxserver/netbox:${NETBOX_DOCKER_TAG:-latest}
    container_name: ${NETBOX_CONTAINER_NAME:-netbox}
    restart: ${NETBOX_RESTART:-unless-stopped}
    depends_on:
      - netbox-postgresql
      - netbox-redis
    healthcheck:
      start_period: 90s
    networks:
      - traefik
    volumes:
      - ./etc/netbox:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - SKIP_SUPERUSER=false
      #Note: default username for the superuser is "admin", not the email address.
      - SUPERUSER_EMAIL=${NETBOX_SUPERUSER_EMAIL:-$ONRAMP_CF_API_EMAIL}
      - SUPERUSER_PASSWORD=${NETBOX_SUPERUSER_PASSWORD:-netbox}
      - ALLOWED_HOST=${NETBOX_CONTAINER_NAME:-netbox}.${HOST_DOMAIN}
      - DB_NAME=${NETBOX_PG_DB_NAME:-netbox}
      - DB_USER=${NETBOX_PG_DB_USER:-netbox}
      - DB_PASSWORD=${NETBOX_PG_DB_PASS}
      - DB_HOST=netbox-postgresql
      #- DB_PORT=5432
      - REDIS_HOST=netbox_redis
      #- REDIS_PORT=<REDIS_PORT>
      #- REDIS_PASSWORD=<REDIS_PASSWORD>
      #- REDIS_DB_TASK=<REDIS_DB_TASK>
      #- REDIS_DB_CACHE=<REDIS_DB_CACHE>
    labels:
      - joyride.host.name=${NETBOX_CONTAINER_NAME:-netbox}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.netbox.entrypoints=websecure
      - traefik.http.routers.netbox.rule=Host(`${NETBOX_CONTAINER_NAME:-netbox}.${HOST_DOMAIN}`)
      - traefik.http.services.netbox.loadbalancer.server.scheme=http # enable if the service wants to connect over https
      - traefik.http.routers.netbox.service=netbox
      - traefik.http.services.netbox.loadbalancer.server.port=8000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  netbox-postgresql:
    image: postgres
    container_name: netbox_postgresql
    restart: unless-stopped
    networks:
      - traefik
    user: "1000:1000"
    volumes:
      - ./etc/netbox/postgresql:/var/lib/postgresql/data
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - POSTGRES_PASSWORD=${NETBOX_PG_DB_PASS:?database password required}
      - POSTGRES_USER=${NETBOX_PG_DB_USER:-netbox}
      - POSTGRES_DB=${NETBOX_PG_DB_NAME:-netbox}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false
      - autoheal=true

  netbox-redis:
    image: redis:alpine
    container_name: netbox_redis
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - netbox-redis:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false
      - autoheal=true