version: '3'

networks:
  traefik:
    external: true

# https://github.com/stautonico/pingvin-share

services:
  pingvin-share:
    image: stonith404/pingvin-share:${PINGVINSHARE_DOCKER_TAG:-latest}
    container_name: ${PINGVINSHARE_CONTAINER_NAME:-pingvin-share}
    restart: ${PINGVINSHARE_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/pingvin-share:/opt/app/backend/data
      - ${PINGVINSHARE_MEDIA_VOLUME:-./media/pingvin-share}:/opt/app/frontend/public/img
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${PINGVINSHARE_CONTAINER_NAME:-share}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.pingvin-share.entrypoints=websecure
      - traefik.http.routers.pingvin-share.rule=Host(`${PINGVINSHARE_CONTAINER_NAME:-pingvin-share}.${HOST_DOMAIN}`)
      - traefik.http.services.pingvin-share.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
