version: '3'

networks:
  traefik:
    external: true

# https://github.com/prometheus/blackbox_exporter

services:
  prometheus-blackbox-exporter:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_DOCKER_TAG:-latest}
    container_name: prometheus-blackbox-exporter
    restart: unless-stopped
    networks:
      - traefik
    command: 
      - '--config.file=/etc/prometheus/conf/blackbox.yml'
    privileged: true
    cap_add: 
      - CAP_NET_RAW
    # ports:
    #   - 9115:9115
    volumes:
      - ./etc/prometheus/conf:/etc/prometheus/conf:ro
    labels:
      - joyride.host.name=blackbox.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.blackbox.rule=Host(`blackbox.${HOST_DOMAIN}`)
      - traefik.http.routers.blackbox.entrypoints=websecure
      - traefik.http.services.blackbox.loadbalancer.server.port=9115
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true