version: '3'

networks:
  default:
    name: traefik

# https://github.com/prometheus/blackbox_exporter

services:
    prometheus-blackbox:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_DOCKER_TAG:-latest}
    container_name: prometheus-blackbox-exporter
    restart: unless-stopped
    command: 
      - '--config.file=/etc/prometheus/conf/blackbox.yml'
    privileged: true
    cap_add: 
      - CAP_NET_RAW
    # ports:
    #   - 9115:9115
    volumes:
      - ./etc/prometheus/conf:/etc/prometheus/conf:ro
    labels:
      - joyride.host.name=blackbox.${HOST_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.blackbox.rule=Host(`blackbox.${HOST_DOMAIN}`)
      - traefik.http.routers.blackbox.entrypoints=websecure
      - traefik.http.routers.blackbox.tls=true
      - traefik.http.routers.blackbox.tls.certresolver=letsencrypt
      - traefik.http.services.blackbox.loadbalancer.server.scheme=http
      - traefik.http.services.blackbox.loadbalancer.server.port=9115