version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/prowlarr

services:
  prowlarr:
    image: linuxserver/prowlarr:${PROWLARR_DOCKER_TAG:-develop}
    container_name: ${PROWLARR_CONTAINER_NAME:-prowlarr}
    restart: ${PROWLARR_RESTART:-unless-stopped}
    volumes:
      - ./etc/prowlarr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${PROWLARR_CONTAINER_NAME:-prowlarr}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_CONTAINER_NAME:-prowlarr}.${HOST_DOMAIN}`)
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
      # Flame dashboard labels
      - flame.type=application # "app" works too
      - flame.name=${PROWLARR_FLAME_NAME:-prowlarr} 
      - flame.url=https://${PROWLARR_CONTAINER_NAME:-prowlarr}.${HOST_DOMAIN}
      - flame.icon=${PROWLARR_FLAME_ICON:-docker} # optional, default is "docker"