version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/redis/redis

services:
  redis:
    image: redis:${REDIS_DOCKER_TAG:-alpine}
    container_name: ${REDIS_CONTAINER_NAME:-redis} 
    restart: ${REDIS_RESTART:-unless-stopped}
    volumes:
      - ./etc/redis:/data 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=false
      - autoheal=true 

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${REDIS_FLAME_NAME:-redis} 
      - flame.url=https://${REDIS_CONTAINER_NAME:-redis}.${HOST_DOMAIN}
      - flame.icon=${REDIS_FLAME_ICON:-docker} # optional, default is "docker"