networks:
  traefik:
    external: true

# description: Remote desktop and support tool
# https://github.com/immense/Remotely

services:
  remotely:
    image: immybot/remotely:${REMOTELY_DOCKER_TAG:-latest}
    container_name: ${REMOTELY_CONTAINER_NAME:-remotely}
    restart: ${REMOTELY_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/remotely:/remotely-data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${REMOTELY_CONTAINER_NAME:-remotely}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.remotely.entrypoints=websecure
      - traefik.http.routers.remotely.rule=Host(`${REMOTELY_CONTAINER_NAME:-remotely}.${HOST_DOMAIN}`)
      - traefik.http.services.remotely.loadbalancer.server.port=5000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
