version: '3'

networks:
  default:
    name: traefik

# https://hub.docker.com/r/linuxserver/sabnzbd

services:
  sabnzbd: 
    image: linuxserver/sabnzbd:${SABNZBD_DOCKER_TAG:-latest}
    container_name: ${SABNZBD_CONTAINER_NAME:-sabnzbd}
    restart: ${SABNZBD_RESTART:-unless-stopped}
    volumes:
      - ./etc/sabnzbd:/config
      - ${MEDIA_DOWNLOADS_VOLUME:-./media/downloads}:/downloads
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    #ports:
      # - 8181:8080 needed to do a fresh setup because of hostname whitelist
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=${SABNZBD_CONTAINER_NAME:-sabnzbd}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.rule=Host(`${SABNZBD_CONTAINER_NAME:-sabnzbd}.${HOST_DOMAIN}`)
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

    # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${SABNZBD_FLAME_NAME:-sabnzbd} 
      - flame.url=https://${SABNZBD_CONTAINER_NAME:-sabnzbd}.${HOST_DOMAIN}
      - flame.icon=${SABNZBD_FLAME_ICON:-cloud-download-outline} # optional, default is "docker"