version: '3'

networks:
  default:
    name: traefik
    
# https://github.com/drakkan/sftpgo

services:
  sftp-server:
    image: drakkan/sftpgo:${SFTP_SERVER_DOCKER_TAG:-latest}
    container_name: ${SFTP_SERVER_CONTAINER_NAME:-sftp-server} 
    restart: ${SFTP_SERVER_RESTART:-unless-stopped}
    volumes:
      - ./etc/sftp-server:/var/lib/sftpgo
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    ports:
      - ${SFTP_SERVER_PORT:-7222:2022}
    labels:
      - joyride.host.name=${SFTP_SERVER_CONTAINER_NAME:-sftp-server}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.sftp-server.entrypoints=websecure
      - traefik.http.routers.sftp-server.rule=Host(`${SFTP_SERVER_CONTAINER_NAME:-sftp-server}.${HOST_DOMAIN}`)
      - traefik.http.services.sftp-server.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${SFTP_SERVER_FLAME_NAME:-sftp-server} 
      - flame.url=https://${SFTP_SERVER_CONTAINER_NAME:-sftp-server}.${HOST_DOMAIN}
      - flame.icon=${SFTP_SERVER_FLAME_ICON:-docker} # optional, default is "docker"