networks:
  traefik:
    external: true

# description: Web-based file sharing tool for local networks
# https://hub.docker.com/r/linuxserver/snapdrop

services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:${SNAPDROP_DOCKER_TAG:-latest}
    container_name: snapdrop
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    volumes:
      - ./etc/snapdrop:/config
    # ports:
    #   - 80:80
    #   - 443:443
    labels:
      - joyride.host.name=${SNAPDROP_CONTAINER_NAME:-snapdrop}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.snapdrop.rule=Host(`${SNAPDROP_CONTAINER_NAME:-snapdrop}.${HOST_DOMAIN}`)
      - traefik.http.routers.snapdrop.entrypoints=websecure
      - traefik.http.services.snapdrop.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
