version: '3'

networks:
  traefik:
    external: true

# https://hub.docker.com/r/linuxserver/sonarr

services:
  sonarr:
    image: linuxserver/sonarr:${SONARR_DOCKER_TAG:-latest}
    container_name: ${SONARR_CONTAINER_NAME:-sonarr}
    restart: ${SONARR_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ${SONARR_CONFIG_VOLUME:-./etc/sonarr}:/config
      - ${MEDIA_SHOWS_VOLUME:-./media/shows}:/tv
      - ${MEDIA_DOWNLOADS_VOLUME:-./media/downloads}:/downloads
      - /dev/rtc:/dev/rtc:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 8989:8989
    environment: 
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000} 
      - TZ=${TZ}
    healthcheck:
      test: curl --fail http://localhost:8989 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      - joyride.host.name=${SONARR_CONTAINER_NAME:-sonarr}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.rule=Host(`${SONARR_CONTAINER_NAME:-sonarr}.${HOST_DOMAIN}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
