version: '3'

networks:
  traefik:
    external: true

# https://github.com/matrix-org/synapse
# docker run -it --rm  -v ./etc/synapse:/data  -e SYNAPSE_SERVER_NAME=synapse.traefikturkey.icu -e SYNAPSE_REPORT_STATS=yes matrixdotorg/synapse:latest generate
services:
  synapse:
    image: ghcr.io/matrix-org/synapse:${SYNAPSE_DOCKER_TAG:-latest}
    container_name: ${SYNAPSE_CONTAINER_NAME:-synapse}
    restart: ${SYNAPSE_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/synapse:/data # <==== this probably needs changed 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_SERVER_NAME=${SYNAPSE_CONTAINER_NAME:-synapse}.${HOST_DOMAIN}
    labels:
      - joyride.host.name=${SYNAPSE_CONTAINER_NAME:-synapse}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.synapse.entrypoints=websecure
      - traefik.http.routers.synapse.rule=Host(`${SYNAPSE_CONTAINER_NAME:-synapse}.${HOST_DOMAIN}`)
      - traefik.http.services.synapse.loadbalancer.server.port=8008
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

