version: '3'

    
# https://github.com/containrrr/watchtower
# https://containrrr.dev/watchtower/notifications/

services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:${WATCHTOWER_DOCKER_TAG:-latest}
    container_name: watchtower
    restart: unless-stopped
    environment: 
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-shoutrrr}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL} 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false 