version: '3'

networks:
  default:
    name: traefik
    
# https://hub.docker.com/r/linuxserver/wireshark

services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:${WIRESHARK_DOCKER_TAG:-latest}
    container_name: ${WIRESHARK_CONTAINER_NAME:-wireshark} 
    restart: ${WIRESHARK_RESTART:-unless-stopped}
    privileged: true
    cap_add:
      - NET_ADMIN
    # security_opt:
    #   - seccomp:unconfined #optional
    network_mode: host   
    ports:
      - 13000:3000 
    volumes:
      - ./etc/wireshark:/config 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${WIRESHARK_CONTAINER_NAME:-wireshark}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.wireshark.entrypoints=websecure
      - traefik.http.routers.wireshark.rule=Host(`${WIRESHARK_CONTAINER_NAME:-wireshark}.${HOST_DOMAIN}`)
      - traefik.http.services.wireshark.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

      # Flame dashboard labels
      
      - flame.type=application # "app" works too
      - flame.name=${WIRESHARK_FLAME_NAME:-wireshark} 
      - flame.url=https://${WIRESHARK_CONTAINER_NAME:-wireshark}.${HOST_DOMAIN}
      - flame.icon=${WIRESHARK_FLAME_ICON:-docker} # optional, default is "docker"