networks:
  traefik:
    external: true

# description: Command-line program to download videos from youtube and other sites
# https://github.com/nbr23/youtube-dl-server

services:
  youtube-dl:
    image: nbr23/youtube-dl-server:${YOUTUBE_DL_DOCKER_TAG:-yt-dlp}
    container_name: ${YOUTUBE_DL_CONTAINER_NAME:-youtube-dl}
    restart: ${YOUTUBE_DL_RESTART:-unless-stopped}
    networks:
      - traefik
    volumes:
      - ./etc/youtube-dl:/youtube-dl
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - joyride.host.name=${YOUTUBE_DL_CONTAINER_NAME:-youtube-dl}.${HOST_DOMAIN}
      - traefik.enable=true
      - traefik.http.routers.youtube-dl.entrypoints=websecure
      - traefik.http.routers.youtube-dl.rule=Host(`${YOUTUBE_DL_CONTAINER_NAME:-youtube-dl}.${HOST_DOMAIN}`)
      - traefik.http.services.youtube-dl.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
