- hosts: localhost
  become: true
  tasks:
    - name: install dependencies
      become: true
      apt:
        update_cache: true
        name:
          - nvidia-driver-535
          - nvidia-dkms-535
        state: present

  roles:
    - nvidia.nvidia_docker
