name: GitHub MafenCI Actions
on: [push]
jobs:
  MafenCI:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '<@${{ secrets.MAFEN_ID }}> {{ EVENT_PAYLOAD.repository.full_name }} has been deployed, please start MafenCI now!'
